#define IDCSD_CLEAR                     101
#define IDCSD_GRID                      102
#define IDCSD_MIRROR                    103
#define IDCSD_POWER                     104
#define IDCSD_SIGNV0                    105
#define IDCSD_SIGNV1                    106
#define IDCSD_ABSTEST                   107
#define IDCSD_SUB0                      108
#define IDCSD_SUB1                      109
#define IDCSD_SUB2                      110
#define IDCSD_ABSTORE                   111
#define IDCSD_GDSIGNALT0                112
#define IDCSD_CREATE                    113
#define IDCSD_GDSIGNALF0                114
#define IDCSD_FFT                       115
#define IDCSD_FFT2                      116
#define IDCSD_SAVEASTEXT                117
#define IDCSD_IDXPOWER                  118
